import Container from "@client/components/common/Container";
import { cn } from "@client/utils";
import Link from "next/link";

export default function Projects() {
  return (
    <Container
      title="Projects - Azat Hafizov"
      description="Azat Hafizov's projects"
    >
      <h1 className="font-bold text-3xl md:text-5xl tracking-tight mb-4 text-black dark:text-white">
        Projects
      </h1>
      <div className="prose dark:prose-dark">
        <p>Interesting projects I've managed to build recently</p>
        <ul>
          <li>
            <div className="mt-6 text-lg font-medium">
              Hyred.ai &mdash; platform for NFTifying resumes
            </div>
            <div>
              Marketplace for candidates selling their resumes as NFTs built
              with Polygon, Next.js, Typescript, GraphQL subscriptions,
              Prisma.io, PostgreSQL, Nexus, Codegen, Hardhat, ethers.js,
              Alchemy, Algolia, AWS Lambda, Terraform.
            </div>
          </li>
          <li>
            <div className="mt-6 text-lg font-medium">
              ANDRO &mdash; no-code tool for video concierges
            </div>
            <div>
              SaaS platform for creating video chatbots using a visual builder.
              &laquo;Concierges&raquo; could be integrated into any website by
              inserting a single script tag. Video questions are generated by a
              custom GAN built on top of CycleGAN and pix2pix in Pytorch.
            </div>
          </li>
          <li>
            <div className="mt-6 text-lg font-medium">
              ROLLO &mdash; &laquo;live commerce&raquo; marketplace
            </div>
            <div>
              Crowdfunding supply contracts on Ethereum, AI assessment of
              sellers' profiles for buyers, CV face recognition-based KYC and
              P2P video streaming capabilities for sellers built with WebRTC.
            </div>
          </li>
        </ul>
      </div>
      <div className="mt-16 mb-6">
        Use Calendly to book a meeting and learn more:
      </div>
      <div className="flex items-center gap-4 md:gap-8">
        {["15 min", "30 min", "1 hour"].map((e: string) => (
          <Link href="/" key={e}>
            <a
              className={cn(
                "flex-1 p-4 border-2 rounded-xl border-slate-200 text-center",
                "cursor-pointer hover:bg-purple-50 hover:border-slate-300",
                "dark:border-slate-700 dark:bg-slate-800",
                "dark:hover:bg-indigo-500 dark:hover:border-indigo-400",
                "transform-gpu transition-colors"
              )}
            >
              {e}
            </a>
          </Link>
        ))}
      </div>
    </Container>
  );
}
